# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20170321114415) do

  create_table "users", force: :cascade do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at",                          null: false
    t.datetime "updated_at",                          null: false
    t.string   "username"
    t.integer  "like_acoustic"
    t.integer  "like_altcountry"
    t.integer  "like_alternative"
    t.integer  "like_ambient"
    t.integer  "like_americana"
    t.integer  "like_artrock"
    t.integer  "like_atmBM"
    t.integer  "like_avantgarde"
    t.integer  "like_beats"
    t.integer  "like_bedroompop"
    t.integer  "like_blackmetal"
    t.integer  "like_bluegrass"
    t.integer  "like_blues"
    t.integer  "like_breakbeat"
    t.integer  "like_breakcore"
    t.integer  "like_chillwave"
    t.integer  "like_chiptune"
    t.integer  "like_christian"
    t.integer  "like_christmas"
    t.integer  "like_classical"
    t.integer  "like_country"
    t.integer  "like_crust"
    t.integer  "like_dance"
    t.integer  "like_dancehall"
    t.integer  "like_darkamb"
    t.integer  "like_deathcore"
    t.integer  "like_deathmet"
    t.integer  "like_deephouse"
    t.integer  "like_depbm"
    t.integer  "like_djent"
    t.integer  "like_doommet"
    t.integer  "like_downtemp"
    t.integer  "like_dreampop"
    t.integer  "like_drone"
    t.integer  "like_drumbass"
    t.integer  "like_dub"
    t.integer  "like_dubstep"
    t.integer  "like_easylistening"
    t.integer  "like_edm"
    t.integer  "like_electronica"
    t.integer  "like_elecpop"
    t.integer  "like_emo"
    t.integer  "like_exp"
    t.integer  "like_fieldrec"
    t.integer  "like_folk"
    t.integer  "like_freejazz"
    t.integer  "like_funk"
    t.integer  "like_fusion"
    t.integer  "like_grock"
    t.integer  "like_glitch"
    t.integer  "like_gospel"
    t.integer  "like_grime"
    t.integer  "like_gcore"
    t.integer  "like_groove"
    t.integer  "like_hrock"
    t.integer  "like_hcore"
    t.integer  "like_hiphop"
    t.integer  "like_house"
    t.integer  "like_idm"
    t.integer  "like_indie"
    t.integer  "like_indust"
    t.integer  "like_instr"
    t.integer  "like_jazz"
    t.integer  "like_krock"
    t.integer  "like_latin"
    t.integer  "like_lofi"
    t.integer  "like_lounge"
    t.integer  "like_mrock"
    t.integer  "like_mdm"
    t.integer  "like_mhc"
    t.integer  "like_metal"
    t.integer  "like_mcore"
    t.integer  "like_min"
    t.integer  "like_mclass"
    t.integer  "like_mconcrete"
    t.integer  "like_nwave"
    t.integer  "like_noise"
    t.integer  "like_npop"
    t.integer  "like_pop"
    t.integer  "like_ppunk"
    t.integer  "like_pcore"
    t.integer  "like_pmetal"
    t.integer  "like_postpunk"
    t.integer  "like_prock"
    t.integer  "like_pviol"
    t.integer  "like_prog"
    t.integer  "like_psych"
    t.integer  "like_punk"
    t.integer  "like_rb"
    t.integer  "like_reg"
    t.integer  "like_rock"
    t.integer  "like_rbilly"
    t.integer  "like_scream"
    t.integer  "like_sgaze"
    t.integer  "like_sing"
    t.integer  "like_sludge"
    t.integer  "like_soul"
    t.integer  "like_strack"
    t.integer  "like_srock"
    t.integer  "like_sword"
    t.integer  "like_strock"
    t.integer  "like_surf"
    t.integer  "like_spop"
    t.integer  "like_swave"
    t.integer  "like_techno"
    t.integer  "like_thrash"
    t.integer  "like_trance"
    t.integer  "like_trap"
    t.integer  "like_thop"
    t.integer  "like_vwave"
    t.integer  "like_vgm"
    t.integer  "like_whouse"
    t.integer  "like_world"
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
    t.index ["username"], name: "index_users_on_username", unique: true
  end

end
