class AddMoreColumnsToModel < ActiveRecord::Migration[5.0]
  def change
  	add_column :users, :like_acoustic, :int
  	add_column :users, :like_altcountry, :int
  	add_column :users, :like_alternative, :int
  	add_column :users, :like_ambient, :int
  	add_column :users, :like_americana, :int
  	add_column :users, :like_artrock, :int
  	add_column :users, :like_atmBM, :int
  	add_column :users, :like_avantgarde, :int
  	add_column :users, :like_beats, :int
  	add_column :users, :like_bedroompop, :int
  	add_column :users, :like_blackmetal, :int
  	add_column :users, :like_bluegrass, :int
  	add_column :users, :like_blues, :int
  	add_column :users, :like_breakbeat, :int
  	add_column :users, :like_breakcore, :int
  	add_column :users, :like_chillwave, :int
  	add_column :users, :like_chiptune, :int
  	add_column :users, :like_christian, :int
  	add_column :users, :like_christmas, :int
  	add_column :users, :like_classical, :int
  	add_column :users, :like_country, :int
  	add_column :users, :like_crust, :int
  	add_column :users, :like_dance, :int
  	add_column :users, :like_dancehall, :int
  	add_column :users, :like_darkamb, :int
  	add_column :users, :like_deathcore, :int
  	add_column :users, :like_deathmet, :int
  	add_column :users, :like_deephouse, :int
  	add_column :users, :like_depbm, :int
  	add_column :users, :like_djent, :int
  	add_column :users, :like_doommet, :int
  	add_column :users, :like_downtemp, :int
  	add_column :users, :like_dreampop, :int
  	add_column :users, :like_drone, :int
  	add_column :users, :like_drumbass, :int
  	add_column :users, :like_dub, :int
  	add_column :users, :like_dubstep, :int
  	add_column :users, :like_easylistening, :int
  	add_column :users, :like_edm, :int
  	add_column :users, :like_electronica, :int
  	add_column :users, :like_elecpop, :int
  	add_column :users, :like_emo, :int
  	add_column :users, :like_exp, :int
  	add_column :users, :like_fieldrec, :int
  	add_column :users, :like_folk, :int
  	add_column :users, :like_freejazz, :int
  	add_column :users, :like_funk, :int
  	add_column :users, :like_fusion, :int
  	add_column :users, :like_grock, :int
  	add_column :users, :like_glitch, :int
  	add_column :users, :like_gospel, :int
  	add_column :users, :like_grime, :int
  	add_column :users, :like_gcore, :int
  	add_column :users, :like_groove, :int
  	add_column :users, :like_hrock, :int
  	add_column :users, :like_hcore, :int
  	add_column :users, :like_hiphop, :int
  	add_column :users, :like_house, :int
  	add_column :users, :like_idm, :int
  	add_column :users, :like_indie, :int
  	add_column :users, :like_indust, :int
  	add_column :users, :like_instr, :int
  	add_column :users, :like_jazz, :int
  	add_column :users, :like_krock, :int
  	add_column :users, :like_latin, :int
  	add_column :users, :like_lofi, :int
  	add_column :users, :like_lounge, :int
  	add_column :users, :like_mrock, :int
  	add_column :users, :like_mdm, :int
  	add_column :users, :like_mhc, :int
  	add_column :users, :like_metal, :int
  	add_column :users, :like_mcore, :int
  	add_column :users, :like_min, :int
  	add_column :users, :like_mclass, :int
  	add_column :users, :like_mconcrete, :int
  	add_column :users, :like_nwave, :int
  	add_column :users, :like_noise, :int
  	add_column :users, :like_npop, :int
  	add_column :users, :like_pop, :int
  	add_column :users, :like_ppunk, :int
  	add_column :users, :like_pcore, :int
  	add_column :users, :like_pmetal, :int
  	add_column :users, :like_postpunk, :int
  	add_column :users, :like_prock, :int
  	add_column :users, :like_pviol, :int
  	add_column :users, :like_prog, :int
  	add_column :users, :like_psych, :int
  	add_column :users, :like_punk, :int
  	add_column :users, :like_rb, :int
  	add_column :users, :like_reg, :int
  	add_column :users, :like_rock, :int
  	add_column :users, :like_rbilly, :int
  	add_column :users, :like_scream, :int
  	add_column :users, :like_sgaze, :int
  	add_column :users, :like_sing, :int
  	add_column :users, :like_sludge, :int
  	add_column :users, :like_soul, :int
  	add_column :users, :like_strack, :int
  	add_column :users, :like_srock, :int
  	add_column :users, :like_sword, :int
  	add_column :users, :like_strock, :int
  	add_column :users, :like_surf, :int
  	add_column :users, :like_spop, :int
  	add_column :users, :like_swave, :int
  	add_column :users, :like_techno, :int
  	add_column :users, :like_thrash, :int
  	add_column :users, :like_trance, :int
  	add_column :users, :like_trap, :int
  	add_column :users, :like_thop, :int
  	add_column :users, :like_vwave, :int
  	add_column :users, :like_vgm, :int
  	add_column :users, :like_whouse, :int
  	add_column :users, :like_world, :int


  end
end